### ISSUE TITLE
Support Selenium

### ISSUE THREAD

**Issue by attiks** [weitzman/upal#3]
Can we also make it possible to support Selenium testing so we can test client side functionality, for the moment we're using http://drupal.org/project/selenium bit it would be nice if this merges to core.

**Comment by weitzman** [comment]
If you want to use PHPUnit and Selenium, then by all means use them. This project won't help or hurt you there.

**Comment by attiks** [comment]
I think it will help, since selenium ide commands can be converted to phpunit and it will make server based selenium testing possible, see also http://blog.boombatower.com/testing-battle-plan

Background: The problem with http://drupal.org/project/selenium as it is now, is that we can not use if for modules on d.o. since it will break testing, so we build our own CI on top of hudson. The other problem is that most of the selenium commands aren't supported, see http://drupal.org/node/1312184 but we agreed to wait for Upal.
