### ISSUE TITLE
Fix the web test cases

### ISSUE THREAD

**Issue by dawehner** [weitzman/upal#5]
If you run tests which uses web test cases they fail, for example

phpunit --debug --configuration /path/to/upal/phpunit.xml core/modules/book/book.test

So the problem i see is the following
$this->content is something like
'$conf['install_profile'] = 'standard';
<!DOCTYPE html>'

This obvious causes problems for uses of assertPattern.
The only place i can see this code is drush_core_pre_site_install($profile);

I will investigate further

**Comment by weitzman** [comment]
I just committed our own versions of assertTrue, assertFalse, and assertThat emthods which return boolean as thats what simpletest expects. I think this fixed the login issue but the book test does not pass still. help wanted.
